const mockResList = [
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/co6lvkimournlhxktdj3",
    name: "Meghna Foods",
    cuisine: ["Biryani, North Indian, Asian"],
    rating: 4.4,
    time: "38 min",
    costForTwo: 400,
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/eom9j3uhsefc0kjwcfbj",
    name: "Bakingo",
    cuisine: ["Bakery", "Desert", "Beverages"],
    rating: 4.5,
    time: "25 min",
    costForTwo: 200,
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/enrxsgw7dtly6y9tv85i",
    name: "Domino's",
    cuisine: ["Pizza", "Italian", "Pasta"],
    rating: 3.9,
    time: "27 min",
    costForTwo: 300,
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2b4f62d606d1b2bfba9ba9e5386fabb7",
    name: "Pizza Hut",
    cuisine: ["Pizza", "Italian", "Pasta"],
    rating: 3.8,
    time: "30 min",
    costForTwo: 300,
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/co6lvkimournlhxktdj3",
    name: "Meghna Foods",
    cuisine: ["Biryani, North Indian, Asian"],
    rating: 4.4,
    time: "38 min",
    costForTwo: 400,
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/eom9j3uhsefc0kjwcfbj",
    name: "Bakingo",
    cuisine: ["Bakery", "Desert", "Beverages"],
    rating: 4.5,
    time: "25 min",
    costForTwo: 200,
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/enrxsgw7dtly6y9tv85i",
    name: "Domino's",
    cuisine: ["Pizza", "Italian", "Pasta"],
    rating: 3.9,
    time: "27 min",
    costForTwo: 300,
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2b4f62d606d1b2bfba9ba9e5386fabb7",
    name: "Pizza Hut",
    cuisine: ["Pizza", "Italian", "Pasta"],
    rating: 3.8,
    time: "30 min",
    costForTwo: 300,
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/co6lvkimournlhxktdj3",
    name: "Meghna Foods",
    cuisine: ["Biryani, North Indian, Asian"],
    rating: 4.4,
    time: "38 min",
    costForTwo: 400,
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/eom9j3uhsefc0kjwcfbj",
    name: "Bakingo",
    cuisine: ["Bakery", "Desert", "Beverages"],
    rating: 4.5,
    time: "25 min",
    costForTwo: 200,
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/enrxsgw7dtly6y9tv85i",
    name: "Domino's",
    cuisine: ["Pizza", "Italian", "Pasta"],
    rating: 3.9,
    time: "27 min",
    costForTwo: 300,
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2b4f62d606d1b2bfba9ba9e5386fabb7",
    name: "Pizza Hut",
    cuisine: ["Pizza", "Italian", "Pasta"],
    rating: 3.8,
    time: "30 min",
    costForTwo: 300,
  },
];

export { mockResList };
